AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Pecuniary Event Handler

Parameters:
  AppName:
    Description: Application name
    Type: String
    Default: Pecuniary
  PecuniaryDbStackParameter:
    Type: String
    Default: pecuniary-db-stack
  PecuniaryTopicsStackParameter:
    Type: String
    Default: pecuniary-topics-stack

Globals:
  Function:
    Timeout: 30

Resources:
  EventService:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: pecuniary-EventService
      Handler: Pecuniary.EventService::Pecuniary.EventService.Function::EventHandlerAsync
      Runtime: dotnetcore2.1
      CodeUri: Pecuniary.EventService/bin/Release/netcoreapp2.1/publish
      MemorySize: 384
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          AccountCreatedEventTopic:
            Fn::ImportValue:
                !Sub ${PecuniaryTopicsStackParameter}-PecuniaryAccountCreatedEventTopicArn
          AccountUpdatedEventTopic:
            Fn::ImportValue:
              !Sub ${PecuniaryTopicsStackParameter}-PecuniaryAccountUpdatedEventTopicArn
          TransactionCreatedEventTopic:
            Fn::ImportValue:
                !Sub ${PecuniaryTopicsStackParameter}-PecuniaryTransactionCreatedEventTopicArn 
          SecurityCreatedEventTopic:
            Fn::ImportValue:
                !Sub ${PecuniaryTopicsStackParameter}-PecuniarySecurityCreatedEventTopicArn
      Events:
        DynamoDB1:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::ImportValue:
                !Sub ${PecuniaryDbStackParameter}-PecuniaryDynamoDbEventStoreStreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
      Policies: 
        - AWSLambdaDynamoDBExecutionRole
        - Statement:
          - Effect: Allow
            Action:
              - sns:ListTopics
              - sns:Publish
            Resource: 
              - Fn::ImportValue:
                 !Sub ${PecuniaryTopicsStackParameter}-PecuniaryAccountCreatedEventTopicArn
              - Fn::ImportValue:
                 !Sub ${PecuniaryTopicsStackParameter}-PecuniaryAccountUpdatedEventTopicArn
              - Fn::ImportValue:
                 !Sub ${PecuniaryTopicsStackParameter}-PecuniaryTransactionCreatedEventTopicArn
              - Fn::ImportValue:
                 !Sub ${PecuniaryTopicsStackParameter}-PecuniarySecurityCreatedEventTopicArn
      Tags:
        AppName: !Ref AppName 
